---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.11.18

platforms:
  - name: puppetlabs/ubuntu-14.04-64-nocm
    box_url:  https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
 
suites:
  - name: app
    run_list:
      - recipe[testca::app]
    attributes:

  - name: default
    run_list:
      - recipe[testca::default]
    attributes:
